#!/usr/bin/env python

#把curl返回的中文转义过的json转成中文输出

import os,sys,re,json

_json=json.loads(raw_input())
if len(sys.argv)>1:
    _json=_json[sys.argv[1]]
print(json.dumps(_json,ensure_ascii=False,indent=4))
